# base image
FROM node:6.13.0

# set working directory
RUN mkdir -p /src/app
WORKDIR /src/app

# add `/src/app/node_modules/.bin` to $PATH
ENV PATH /src/app/node_modules/.bin:$PATH

# copy source code
COPY . /src/app

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install

# port
EXPOSE 3000

# start app
CMD ["npm", "start"]