# base image
FROM node:8

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# copy source code
COPY . /usr/src/app

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install

# port
EXPOSE 3002

# start app
CMD ["npm", "start"]